CREATE TABLE Cart
(
    Id NVARCHAR(250) PRIMARY KEY,
    Quantity INT DEFAULT 0
);

CREATE TABLE CartItem
(
    Id NVARCHAR(250) PRIMARY KEY,
    Name NVARCHAR(250),
    Description NVARCHAR(250),
    CartId NVARCHAR(36) NOT NULL,
    FOREIGN KEY(CartId) REFERENCES Cart(Id)
);
